! add notes here (p.106)

attributes(global) subroutine s1(raceCount, atomicCount)
    implicit none 
    integer :: raceCount, atomicCount 
    integer :: tmp 
    integer, shared :: sharedCount 

    if (threadIdx%x == 1) sharedCount = 0 
    call syncthreads() 

    raceCount = raceCount + 1 
    tmp = atomicAdd(shareCount, 1)
    call syncthreads() 

    if (threadIdx%x == 1) tmp = atomicAdd(atomicCount, sharedCount)
end subroutine s1 

    